OUTPUT:
b'\r\n(WERI_cwatm) C:\\Users\\psh2610\\Documents\\mehdi\\CWatM\\Toolkit\\Calibration\\runs_calibration3\\13_128>call C:/Users/psh2610/WERI_cwatm/Scripts/activate \r\nCWATM - Community Water Model  1.5  Date:  2025/04/27 15:58  \r\nInternational Institute of Applied Systems Analysis (IIASA)\r\nRunning under platform:  Windows\r\n-----------------------------------------------------------\r\n'
ERRORS:
b'C:\\Users\\psh2610\\WERI_cwatm\\Lib\\site-packages\\osgeo\\gdal.py:314: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.\r\n  warnings.warn(\r\nERROR 1: Deleting D:\\out_cwatm_30min_khozestan_26Apr\\basin.tif failed:\nPermission denied\nERROR 4: Attempt to create new tiff file `D:\\out_cwatm_30min_khozestan_26Apr\\basin.tif\' failed: D:\\out_cwatm_30min_khozestan_26Apr\\basin.tif: file used by other process\nTraceback (most recent call last):\r\n  File "C:\\Users\\psh2610\\Documents\\mehdi\\CWatM\\run_cwatm.py", line 39, in <module>\r\n    main(settings, args)\r\n    ~~~~^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\psh2610\\Documents\\mehdi\\CWatM\\cwatm\\run_cwatm.py", line 332, in main\r\n    success, last_dis = CWATMexe(settingsfile[0])\r\n                        ~~~~~~~~^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\psh2610\\Documents\\mehdi\\CWatM\\cwatm\\run_cwatm.py", line 133, in CWATMexe\r\n    CWATM = CWATModel()\r\n  File "C:\\Users\\psh2610\\Documents\\mehdi\\CWatM\\cwatm\\cwatm_initial.py", line 166, in __init__\r\n    self.routing_kinematic_module.initial()\r\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\r\n  File "C:\\Users\\psh2610\\Documents\\mehdi\\CWatM\\cwatm\\hydrological_modules\\routing_reservoirs\\routing_kinematic.py", line 210, in initial\r\n    report(self.var.catchment,file)\r\n    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\psh2610\\Documents\\mehdi\\CWatM\\cwatm\\management_modules\\data_handling.py", line 1938, in report\r\n    ds.SetGeoTransform(geo)  # specify coords\r\n    ^^^^^^^^^^^^^^^^^^\r\nAttributeError: \'NoneType\' object has no attribute \'SetGeoTransform\'\r\n'